[package]
name = "snix-cli-store"
version = "0.1.0"
edition = "2024"
rust-version.workspace = true

[[bin]]
name = "snix-store"
path = "src/main.rs"

[dependencies]
async-stream.workspace = true
clap = { workspace = true, features = ["derive", "env"] }
data-encoding.workspace = true
futures.workspace = true
mimalloc.workspace = true
nix-compat = { path = "../../nix-compat", features = ["async", "serde"] }
petgraph.workspace = true
prost.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_with.workspace = true
snix-castore = { path = "../../castore", features = ["serde"] }
snix-cli.path = "../base"
snix-store.path = "../../store"
snix-tracing = { path = "../../tracing", features = [
  "clap",
  "reqwest",
  "tonic",
] }
tokio = { workspace = true, features = ["fs", "macros", "rt-multi-thread"] }
tokio-listener = { workspace = true, features = [
  "clap",
  "multi-listener",
  "sd_listen",
  "tonic014",
] }
tonic.workspace = true
tonic-health.workspace = true
tonic-reflection = { workspace = true, optional = true }
tonic-tracing-opentelemetry = { workspace = true, optional = true }
tracing.workspace = true
tracing-indicatif.workspace = true

[features]
default = ["fuse", "otlp", "tonic-reflection"]
fuse = ["snix-castore/fuse", "snix-store/fs"]
virtiofs = ["snix-castore/virtiofs", "snix-store/fs"]
tonic-reflection = ["dep:tonic-reflection"]
otlp = ["snix-tracing/otlp", "dep:tonic-tracing-opentelemetry"]
tracing-chrome = ["snix-tracing/chrome"]
tracing-tracy = ["snix-tracing/tracy"]
xp-store-composition-cli = [
  "snix-store/xp-composition-cli",
  "snix-castore/xp-composition-cli",
]
